### ISSUE TITLE
Upgrade to 2.0

### ISSUE THREAD

**Issue by maniackcrudelis** [M5oul/linuxdash_ynh#3]
There's a new version 2.0 https://github.com/afaqurk/linux-dash/releases/tag/2.0

But, I tried for severals hours and can't make it work.
There're 3 things to know about this upgrade

- python-server.py doesn't exist anymore, you have to use app/server/index.py instead.
- And so you have to change the port in this file.
- And, probably the problem I have, linux dash uses now angularJS (which is really better for the interface !), but the js code is get from google...
https://github.com/afaqurk/linux-dash/blob/master/index.html#L27
I have a lot of problems with that, and in all my tests, I can't have the interface of linux dash, only the charts.

**Comment by yalh76** [comment]
already at a more recent version than 2.0
